plt.close('all')

fig1 = plt.figure(1, figsize=(16,12))
fig1.canvas.set_window_title("BrO_column_NHstations")
ax11 = plt.subplot(411)
GOME_data_list.sel(lat=82.5, lon=-62.3, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=82.5, lon=360-62.3, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=82.5, lon=360-62.3, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=82.5, lon=360-62.3, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=82.5, lon=360-62.3, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax11.set_title("Alert (Canada): 82.50 N, 62.30 W, 210 m a.s.l.")
ax12 = plt.subplot(412)
GOME_data_list.sel(lat=71.32, lon=-156.61, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=71.32, lon=360-156.61, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=71.32, lon=360-156.61, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=71.32, lon=360-156.61, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=71.32, lon=360-156.61, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax12.set_title("Barrow (Alaska): 71.32 N, 156.61 W, 8 m a.s.l.")
ax13 = plt.subplot(413)
GOME_data_list.sel(lat=78.9, lon=11.88, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=78.9, lon=11.88, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=78.9, lon=11.88, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=78.9, lon=11.88, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=78.9, lon=11.88, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax13.set_title("Zeppelin Mountain (Norway): 78.90 N, 11.88 E, 474 m a.s.l.")
ax14 = plt.subplot(414)
GOME_data_list.sel(lat=72.75, lon=-38.48, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=72.75, lon=360-38.48, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=72.75, lon=360-38.48, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=72.75, lon=360-38.48, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=72.75, lon=360-38.48, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax14.set_title("Summit (Greenland): 72.54 N, 38.48 W, 3238 m a.s.l.")
ax14.legend(frameon=False, loc='best')
for ax in fig1.axes:
    ax.set_ylabel("")
    ax.set_xlabel("")
ax13.set_ylabel("BrO (10$^{13}$ molec/cm$^2$)", y=1.25)

fig2 = plt.figure(2, figsize=(16,12))
fig2.canvas.set_window_title("BrO_column_SHstations")
ax21 = plt.subplot(411)
GOME_data_list.sel(lat=-64.77, lon=-64.05, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=-64.77, lon=360-64.05, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=-64.77, lon=360-64.05, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=-64.77, lon=360-64.05, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=-64.77, lon=360-64.05, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax21.set_title("Palmer Station (Antarctica, USA): 64.77 S, 64.05 W, 21 m a.s.l.")
ax22 = plt.subplot(412)
GOME_data_list.sel(lat=-70.68, lon=-8.26, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=-70.68, lon=360-8.26, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=-70.68, lon=360-8.26, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=-70.68, lon=360-8.26, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=-70.68, lon=360-8.26, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax22.set_title("Neumeyer Station (Antarctica, Germany): 70.68 S, 8.26 W, 43 m a.s.l.")
ax23 = plt.subplot(413)
GOME_data_list.sel(lat=-77.85, lon=166.78, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=-77.85, lon=166.78, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=-77.85, lon=166.78, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=-77.85, lon=166.78, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=-77.85, lon=166.78, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax23.set_title("Arrival Heights (Antarctica, New Zealand): 77.85 S, 166.78 E, 22 m a.s.l.")
ax24 = plt.subplot(414)
#GOME_data_list.sel(lat=-89, lon=24.8, method='nearest')['BrO'].plot(color='red', marker='x', ls='none', label='obs')
(EMAC_data_list_ref.sel(lat=-89, lon=360-24.8, method='nearest')['BrO_column']*1e-13).plot(color='black', label='ref')
(EMAC_data_list_fysic.sel(lat=-89, lon=360-24.8, method='nearest')['BrO_column']*1e-13).plot(color='cornflowerblue', ls='--', label='fysic')
(EMAC_data_list.sel(lat=-89, lon=360-24.8, method='nearest')['BrO_column']*1e-13).plot(color='blue', label='mysic')
(EMAC_data_list_mysic_rs.sel(lat=-89, lon=360-24.8, method='nearest')['BrO_column']*1e-13).plot(color='cyan', ls=':', label='mysic_rs')
ax24.set_title("South Pole Station (Antarctica, USA): 89.98 S, 24.8 W, 2810 m a.s.l.")
#ax24.legend(frameon=False, loc='best')
for ax in fig2.axes:
    ax.set_ylabel("")
    ax.set_xlabel("")
ax23.set_ylabel("BrO (10$^{13}$ molec/cm$^2$)", y=1.25)
# Show it
plt.show(block=False)
